FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev git nodejs npm \
    && pip install semgrep bandit pylint \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app

CMD ["celery", "-A", "app.workers.celery_app", "worker", "-l", "info", "-Q", "celery"]
